In [1]:
print(10+10)

20


In [4]:
print(40-20)

20


In [5]:
40-20

20

In [8]:
print(2+2)
print(3+4)


4
7


In [10]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [11]:
print(type(arr1))

<class 'numpy.ndarray'>


In [12]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr3 = np.array([
                    [[1,2,3],[4,5,6]],
                    [[7,8,9],[10,11,12]]
                ])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [14]:
print(arr1)
print(arr2)
print(arr3)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [18]:
print(arr1)
print(arr1.ndim)

[1 2 3 4 5]
1


In [19]:
print(arr2.ndim)

2


In [20]:
print(arr3.ndim)

3


In [21]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [22]:
arr2.shape

(2, 3)

In [24]:
arr1.size

5

Numpy Build-in Array Creation Function

In [28]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [31]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [33]:
np.linspace(0, 2, 5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [37]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

NumPy Random Module

In [44]:
np.random.rand()

0.3812977125397018

In [48]:
np.random.rand(3,3)

array([[0.4238531 , 0.47993735, 0.98246189],
       [0.27329791, 0.70443327, 0.15578213],
       [0.67300269, 0.46007827, 0.28388686]])

In [49]:
np.random.rand(2,3)

array([[0.84745212, 0.89885678, 0.27955964],
       [0.96846059, 0.09716259, 0.41564152]])

In [53]:
np.random.randn(3,3)

array([[-0.14857086, -0.24772462,  0.35462804],
       [ 1.09254207, -0.85313892,  0.47747901],
       [ 0.3649349 , -0.42904398, -1.00713217]])

In [97]:
np.random.randint(50,100)

76

In [104]:
np.random.randint(1, 100, (2,2))

array([[38, 30],
       [84, 12]])

In [127]:
list1 = [5,2,67,1,7]
np.random.choice(list1)

7

In [126]:
fruits = ["Apple", "Orange", "kiwi", "pie", "Mango"]
np.random.choice(fruits)

'Orange'

In [142]:
np.random.seed(3)
np.random.randint(1, 100, (3,3))

array([[25,  4, 57],
       [73,  1, 22],
       [20, 75, 42]])

In [5]:
import numpy as np
arr = np.array([10,20,30,40,50,60,70,80])
print(arr)

[10 20 30 40 50 60 70 80]


In [3]:
type(arr)

numpy.ndarray

In [6]:
print(arr)

[10 20 30 40 50 60 70 80]


In [7]:
print(arr[5])

60


In [8]:
arr[4:7]

array([50, 60, 70])

In [9]:
arr1 = np.array([4,5,6,7])
arr2 = np.array([1,2,3,4])
print(arr1 + arr2)

[ 5  7  9 11]


In [10]:
print(arr1 - arr2)

[3 3 3 3]


In [11]:
print(arr1 * arr2)

[ 4 10 18 28]


In [12]:
print(arr1)

[4 5 6 7]


In [14]:
print(arr1)

[4 5 6 7]


In [15]:
arr1 + 3

array([ 7,  8,  9, 10])

In [16]:
arr1 - 3

array([1, 2, 3, 4])

In [17]:
arr1 ** 2

array([16, 25, 36, 49])

In [18]:
np.sqrt(arr1)

array([2.        , 2.23606798, 2.44948974, 2.64575131])

In [19]:
arr = np.array([4,5,6,7,8,5,4,3,4,5,6,75])
print(arr)

[ 4  5  6  7  8  5  4  3  4  5  6 75]


In [20]:
arr.min()

3

In [21]:
arr.max()

75

In [22]:
print(arr)

[ 4  5  6  7  8  5  4  3  4  5  6 75]


In [23]:
np.sum(arr)

132

In [24]:
np.mean(arr)

11.0

In [ ]:
arr = np.array([
                [1,2,3],
                [4,5,6],
                [7,8,9]
            ])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
np.min(arr)

1

In [28]:
np.max(arr)

9

In [29]:
np.sum(arr)

45

In [33]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
np.sum(arr, axis=0)

array([12, 15, 18])

In [31]:
np.sum(arr)

45

In [36]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [43]:
arr = np.arange(10, 20)
print(arr)

[10 11 12 13 14 15 16 17 18 19]


In [44]:
arr.reshape(2,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [45]:
arr2 = np.arange(1,10)
print(arr2)

[1 2 3 4 5 6 7 8 9]


In [46]:
arr2.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
arr3 = np.arange(1, 13)
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [50]:
arr4 = arr3.reshape(4, 3)
print(arr4)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [52]:
arr4.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
list1 = [1,2,3,4]
list1 + 4

In [54]:
arr = np.array([1,2,3,4])
arr + 4

array([5, 6, 7, 8])

In [55]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr1 + arr2

array([5, 7, 9])

In [56]:
arr1 = np.array([[1,2,3],
                 [4,5,6]])

arr2 = np.array([4,5,6])
arr1 + arr2

array([[ 5,  7,  9],
       [ 8, 10, 12]])

In [57]:
A = np.array([[1,2],
              [4,5]])

B = np.array([[10,20],
              [40,50]])

np.dot(A,B)

array([[ 90, 120],
       [240, 330]])

In [58]:
A

array([[1, 2],
       [4, 5]])

In [59]:
A.T

array([[1, 4],
       [2, 5]])

In [60]:
arr = np.array([
                [1,2,3],
                [4,5,7],
                [8,9,10]])
print(arr)

[[ 1  2  3]
 [ 4  5  7]
 [ 8  9 10]]


In [62]:
np.sum(arr, axis=0)

array([13, 16, 20])

In [63]:
np.sum(arr, axis=1)

array([ 6, 16, 27])