In [1]:
print(10+10)

20


In [4]:
print(40-20)

20


In [5]:
40-20

20

In [8]:
print(2+2)
print(3+4)


4
7


In [10]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [11]:
print(type(arr1))

<class 'numpy.ndarray'>


In [12]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr3 = np.array([
                    [[1,2,3],[4,5,6]],
                    [[7,8,9],[10,11,12]]
                ])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [14]:
print(arr1)
print(arr2)
print(arr3)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [18]:
print(arr1)
print(arr1.ndim)

[1 2 3 4 5]
1


In [19]:
print(arr2.ndim)

2


In [20]:
print(arr3.ndim)

3


In [21]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [22]:
arr2.shape

(2, 3)

In [24]:
arr1.size

5

Numpy Build-in Array Creation Function

In [28]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [31]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [33]:
np.linspace(0, 2, 5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [37]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

NumPy Random Module

In [44]:
np.random.rand()

0.3812977125397018

In [48]:
np.random.rand(3,3)

array([[0.4238531 , 0.47993735, 0.98246189],
       [0.27329791, 0.70443327, 0.15578213],
       [0.67300269, 0.46007827, 0.28388686]])

In [49]:
np.random.rand(2,3)

array([[0.84745212, 0.89885678, 0.27955964],
       [0.96846059, 0.09716259, 0.41564152]])

In [53]:
np.random.randn(3,3)

array([[-0.14857086, -0.24772462,  0.35462804],
       [ 1.09254207, -0.85313892,  0.47747901],
       [ 0.3649349 , -0.42904398, -1.00713217]])

In [97]:
np.random.randint(50,100)

76

In [104]:
np.random.randint(1, 100, (2,2))

array([[38, 30],
       [84, 12]])

In [127]:
list1 = [5,2,67,1,7]
np.random.choice(list1)

7

In [126]:
fruits = ["Apple", "Orange", "kiwi", "pie", "Mango"]
np.random.choice(fruits)

'Orange'

In [142]:
np.random.seed(3)
np.random.randint(1, 100, (3,3))

array([[25,  4, 57],
       [73,  1, 22],
       [20, 75, 42]])